---

- name: Variable Practise
  hosts: all
  
  vars:
      username: hrishi
      package_name: nginx
  tasks:
     - name: variable declration
       ansible.builtin.debug:
          msg: "Hello {{ username }}"
     - name: package installation
       ansible.builtin.package:
         name: "{{ package_name }}"
         state: present


